language: node_js
notifications:
  irc: "irc.blitzed.org#stonecypher-builds"
  recipients:
    - stonecypher@gmail.com
node_js:
  - "0.11"
  - "0.10"
before_script: cd src && npm install
script: npm test